standard = [
  "accountsservice",
  "alsa-firmware",
  "alsa-plugins",
  "alsa-utils",
  "aria2",
  "awesome-terminal-fonts",
  "baobab",
  "base",
  "base-devel",
  "bash-completion",
  "bind",
  "bluez",
  "bluez-hid2hci",
  "bluez-libs",
  "bluez-obex",
  "bluez-utils",
  "bpftune-git",
  "brave-bin",
  "btop",
  "btrfs-assistant",
  "btrfs-progs",
  "cachy-update",
  "cachyos-fish-config",
  "cachyos-gaming-applications",
  "cachyos-gaming-meta",
  "cachyos-hello",
  "cachyos-hooks",
  "cachyos-kernel-manager",
  "cachyos-keyring",
  "cachyos-micro-settings",
  "cachyos-mirrorlist",
  "cachyos-packageinstaller",
  "cachyos-plymouth-bootanimation",
  "cachyos-plymouth-theme",
  "cachyos-rate-mirrors",
  "cachyos-settings",
  "cachyos-snapper-support",
  "cachyos-v3-mirrorlist",
  "cachyos-v4-mirrorlist",
  "cachyos-wallpapers",
  "cachyos-zsh-config",
  "cantarell-fonts",
  "chwd",
  "clang",
  "cpupower",
  "cronie",
  "cryptsetup",
  "decibels",
  "device-mapper",
  "diffutils",
  "dmemcg-booster",
  "dmidecode",
  "dmraid",
  "dnsmasq",
  "dosfstools",
  "duf",
  "e2fsprogs",
  "ed",
  "efibootmgr",
  "efitools",
  "egl-wayland",
  "ethtool",
  "exfatprogs",
  "f2fs-tools",
  "fastfetch",
  "file-roller",
  "fsarchiver",
  "fuse2",
  "fwupd",
  "gamemode",
  "gamescope-session-cachyos",
  "gdm",
  "git",
  "git-lfs",
  "github-cli",
  "glab",
  "glances",
  "gnome-backgrounds",
  "gnome-boxes",
  "gnome-calculator",
  "gnome-control-center",
  "gnome-disk-utility",
  "gnome-keyring",
  "gnome-power-manager",
  "gnome-remote-desktop",
  "gnome-shell",
  "gnome-software",
  "gnome-text-editor",
  "gnome-tweaks",
  "graphicsmagick",
  "gst-libav",
  "gst-plugin-pipewire",
  "gst-plugin-va",
  "gst-plugins-bad",
  "gst-plugins-ugly",
  "gufw",
  "gvfs-afc",
  "gvfs-gphoto2",
  "gvfs-mtp",
  "gvfs-nfs",
  "gvfs-smb",
  "hdparm",
  "hwdetect",
  "hwinfo",
  "inetutils",
  "intel-media-driver",
  "intel-media-sdk",
  "intel-ucode",
  "iptables",
  "iwd",
  "jfsutils",
  "less",
  "lib32-nvidia-utils",
  "lib32-opencl-nvidia",
  "lib32-vulkan-icd-loader",
  "lib32-vulkan-intel",
  "libdvdcss",
  "libgsf",
  "libnma",
  "libopenraw",
  "libreoffice-fresh",
  "libva-nvidia-driver",
  "limine",
  "limine-mkinitcpio-hook",
  "limine-snapper-sync",
  "linux-cachyos",
  "linux-cachyos-headers",
  "linux-cachyos-nvidia-open",
  "linux-firmware",
  "logrotate",
  "loupe",
  "lsb-release",
  "lshw",
  "lsscsi",
  "lutris",
  "lvm2",
  "lychee",
  "malcontent",
  "man-db",
  "man-pages",
  "mdadm",
  "mesa-utils",
  "micro",
  "mise",
  "mkinitcpio",
  "modemmanager",
  "mtools",
  "nano",
  "nautilus-python",
  "netctl",
  "networkmanager",
  "networkmanager-openvpn",
  "nfs-utils",
  "nginx",
  "nilfs-utils",
  "noto-fonts",
  "noto-fonts-cjk",
  "noto-fonts-emoji",
  "npm",
  "nss-mdns",
  "nvidia-prime",
  "nvidia-settings",
  "nvidia-utils",
  "opencl-nvidia",
  "openssh",
  "os-prober",
  "pacman-contrib",
  "paru",
  "pavucontrol",
  "perl",
  "perl-image-exiftool",
  "pipewire-alsa",
  "pipewire-pulse",
  "pkgfile",
  "plocate",
  "plymouth",
  "podman",
  "podman-compose",
  "podman-docker",
  "poppler-glib",
  "postgresql",
  "postgresql-libs",
  "power-profiles-daemon",
  "profile-sync-daemon",
  "ptyxis",
  "pv",
  "python",
  "python-defusedxml",
  "python-docutils",
  "python-packaging",
  "rclone",
  "rebuild-detector",
  "reflector",
  "ripgrep",
  "rsync",
  "ruby-erb",
  "s-nail",
  "sg3_utils",
  "shelly",
  "shelly-flatpak-backend",
  "simple-scan",
  "smartmontools",
  "snapper",
  "snapshot",
  "sof-firmware",
  "starship",
  "sudo",
  "switcheroo-control",
  "sysfsutils",
  "texinfo",
  "ttf-bitstream-vera",
  "ttf-dejavu",
  "ttf-jetbrains-mono-nerd",
  "ttf-liberation",
  "ttf-meslo-nerd",
  "ttf-opensans",
  "ttf-roboto",
  "ufw",
  "ufw-extras",
  "unrar",
  "unzip",
  "upower",
  "usage",
  "usb_modeswitch",
  "usbutils",
  "valkey",
  "vim",
  "vulkan-icd-loader",
  "vulkan-intel",
  "wget",
  "which",
  "wireplumber",
  "wpa_supplicant",
  "xdg-user-dirs",
  "xfsprogs",
  "xl2tpd",
  "xterm",
  "yarn",
]

aur = [
  "antigravity-cli",
  "bibata-cursor-theme-bin",
  "debtap",
  "envycontrol",
  "google-chrome",
  "google-cloud-cli",
  "jenkins-cli",
  "nautilus-open-in-ptyxis",
  "runit-systemd",
  "ttf-google-sans",
  "visual-studio-code-bin",
]

flatpak = [
  "com.bilingify.readest",
  "com.bitwarden.desktop",
  "com.github.finefindus.eyedropper",
  "com.github.marhkb.Pods",
  "com.github.tchx84.Flatseal",
  "com.github.xournalpp.xournalpp",
  "com.mattjakeman.ExtensionManager",
  "io.anytype.anytype",
  "io.github.diegopvlk.Cine",
  "io.github.flattool.Warehouse",
  "io.github.peazip.PeaZip",
  "io.github.totoshko88.RustConn",
  "net.ankiweb.Anki",
  "net.nokyan.Resources",
  "org.freedownloadmanager.Manager",
  "org.gimp.GIMP",
  "org.gnome.Papers",
  "org.gnome.SoundRecorder",
  "org.gnome.font-viewer",
  "org.inkscape.Inkscape",
  "org.mozilla.firefox",
  "org.pgadmin.pgadmin4",
  "org.videolan.VLC",
]
